services:
  # mongodb:
  #   image: mongo:7
  #   container_name: wp-writer-mongodb
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - wp-writer-net

  # redis:
  #   image: redis:7-alpine
  #   container_name: wp-writer-redis
  #   networks:
  #     - wp-writer-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wp-writer-backend
    network_mode: "host"
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
      - wp_images:/tmp/wp_images

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    env_file:
      - .env
    network_mode: "host"
    container_name: wp-writer-worker
    command: python -m app.main
    volumes:
      - ./worker/app:/app/app
      - wp_images:/tmp/wp_images

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wp-writer-frontend
    network_mode: "host"
    ports:
      - "5174:5173"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html

volumes:
  wp_images:
