"""
Image Service — generate thumbnails and section images using Gemini or OpenAI.
"""

import asyncio
import base64
import os
import uuid
from bson import ObjectId
from app.database import ai_providers_col


async def _get_provider(provider_id: str = None):
    """Get an AI provider by ID, or the first available if no ID provided."""
    if provider_id:
        doc = await ai_providers_col.find_one({"_id": ObjectId(provider_id)})
        if not doc:
            raise Exception(f"AI provider not found: {provider_id}")
        return doc
    doc = await ai_providers_col.find_one()
    if not doc:
        raise Exception("No AI provider configured. Please add one in Settings.")
    return doc


async def _get_gemini_key() -> str:
    """Get a Gemini API key. Falls back to any provider's key if only Gemini is available."""
    doc = await ai_providers_col.find_one({"provider_type": "gemini"})
    if doc:
        return doc["api_key"]
    raise Exception(
        "No Gemini provider configured. Add a Gemini API key in Settings to generate images."
    )


async def _get_openai_key() -> str:
    """Get an OpenAI API key."""
    doc = await ai_providers_col.find_one({"provider_type": "openai"})
    if doc:
        return doc["api_key"]
    raise Exception(
        "No OpenAI provider configured. Add an OpenAI API key in Settings to generate images."
    )


async def generate_image_with_gemini(
    prompt: str, save_dir: str = "/tmp/wp_images"
) -> str:
    """Generate an image using Gemini and save it locally. Returns the file path."""
    from google import genai
    from google.genai import types

    api_key = await _get_gemini_key()
    client = genai.Client(api_key=api_key)

    response = client.models.generate_content(
        model="gemini-2.0-flash-exp-image-generation",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_modalities=["TEXT", "IMAGE"],
        ),
    )

    os.makedirs(save_dir, exist_ok=True)

    for part in response.candidates[0].content.parts:
        if part.inline_data and part.inline_data.mime_type.startswith("image/"):
            ext = part.inline_data.mime_type.split("/")[1]
            filename = f"{uuid.uuid4()}.{ext}"
            filepath = os.path.join(save_dir, filename)
            with open(filepath, "wb") as f:
                f.write(part.inline_data.data)

            # Resize to 150x150 square
            from app.utils.image_utils import resize_to_square

            resized_path = resize_to_square(filepath, size=150)

            return resized_path

    raise Exception("No image was generated by Gemini")


async def generate_image_with_openai(
    prompt: str, model: str = "dall-e-3", save_dir: str = "/tmp/wp_images"
) -> str:
    """Generate an image using OpenAI DALL-E and save it locally. Returns the file path."""
    from openai import AsyncOpenAI
    import httpx

    api_key = await _get_openai_key()
    client = AsyncOpenAI(api_key=api_key)

    response = await client.images.generate(
        model=model,
        prompt=prompt,
        size="1024x1024",
        quality="standard",
        n=1,
    )

    image_url = response.data[0].url

    async with httpx.AsyncClient() as http_client:
        image_response = await http_client.get(image_url)
        image_response.raise_for_status()
        image_data = image_response.content

    os.makedirs(save_dir, exist_ok=True)
    ext = "png"
    filename = f"{uuid.uuid4()}.{ext}"
    filepath = os.path.join(save_dir, filename)
    with open(filepath, "wb") as f:
        f.write(image_data)

    # Resize to 150x150 square
    from app.utils.image_utils import resize_to_square

    resized_path = resize_to_square(filepath, size=150)

    return resized_path


async def generate_image(
    prompt: str,
    provider_id: str = None,
    model_name: str = None,
    save_dir: str = "/tmp/wp_images",
    max_retries: int = 1,
    delay: int = 30,
    on_retry: callable = None,
) -> str:
    """Generate an image using the specified provider and save it locally with retry logic."""
    provider = await _get_provider(provider_id)
    provider_type = provider.get("provider_type")

    for attempt in range(max_retries):
        try:
            if provider_type == "openai":
                model = model_name or "dall-e-3"
                return await generate_image_with_openai(prompt, model, save_dir)
            elif provider_type == "gemini":
                return await generate_image_with_gemini(prompt, save_dir)
            else:
                raise Exception(
                    f"Image generation not supported for provider type: {provider_type}"
                )
        except Exception as e:
            if attempt < max_retries - 1:
                print(
                    f"[RETRY] Image generation failed. Retrying in {delay}s... ({attempt + 1}/{max_retries}): {e}"
                )
                if on_retry:
                    await on_retry(attempt + 1, max_retries)
                await asyncio.sleep(delay)
            else:
                raise e


async def generate_thumbnail(
    topic: str,
    title: str,
    provider_id: str = None,
    model_name: str = None,
    on_retry: callable = None,
) -> str:
    """Generate a blog post thumbnail."""
    prompt = f"""Create a professional, eye-catching blog post thumbnail image for:
Topic: {topic}
Title: {title}

The image should be:
- Modern and professional
- Suitable as a blog post featured image
- Square aspect ratio (1:1)
- Clean with good visual hierarchy
- No text overlay needed"""

    return await generate_image(prompt, provider_id, model_name, on_retry=on_retry)


async def generate_section_image(
    topic: str,
    section_title: str,
    provider_id: str = None,
    model_name: str = None,
    on_retry: callable = None,
) -> str:
    """Generate an image for a blog post section."""
    prompt = f"""Create a professional illustration for a blog section:
Blog topic: {topic}
Section: {section_title}

The image should be:
- Relevant to the section topic
- Professional and clean
- Suitable for a blog post
- Informative or illustrative"""

    return await generate_image(prompt, provider_id, model_name, on_retry=on_retry)
