"""
Image Service — generate thumbnails and section images using Gemini.
"""
import base64
import os
import uuid
from app.database import ai_providers_col


async def _get_gemini_key() -> str:
    """Get a Gemini API key. Falls back to any provider's key if only Gemini is available."""
    doc = await ai_providers_col.find_one({"provider_type": "gemini"})
    if doc:
        return doc["api_key"]
    raise Exception("No Gemini provider configured. Add a Gemini API key in Settings to generate images.")


async def generate_image(prompt: str, save_dir: str = "/tmp/wp_images") -> str:
    """Generate an image using Gemini and save it locally. Returns the file path."""
    from google import genai
    from google.genai import types

    api_key = await _get_gemini_key()
    client = genai.Client(api_key=api_key)

    response = client.models.generate_content(
        model="gemini-2.0-flash-preview-image-generation",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_modalities=["TEXT", "IMAGE"],
        ),
    )

    os.makedirs(save_dir, exist_ok=True)

    for part in response.candidates[0].content.parts:
        if part.inline_data and part.inline_data.mime_type.startswith("image/"):
            ext = part.inline_data.mime_type.split("/")[1]
            filename = f"{uuid.uuid4()}.{ext}"
            filepath = os.path.join(save_dir, filename)
            with open(filepath, "wb") as f:
                f.write(part.inline_data.data)
            return filepath

    raise Exception("No image was generated by Gemini")


async def generate_thumbnail(topic: str, title: str) -> str:
    """Generate a blog post thumbnail."""
    prompt = f"""Create a professional, eye-catching blog post thumbnail image for:
Topic: {topic}
Title: {title}

The image should be:
- Modern and professional
- Suitable as a blog post featured image
- 16:9 aspect ratio
- Clean with good visual hierarchy
- No text overlay needed"""

    return await generate_image(prompt)


async def generate_section_image(topic: str, section_title: str) -> str:
    """Generate an image for a blog post section."""
    prompt = f"""Create a professional illustration for a blog section:
Blog topic: {topic}
Section: {section_title}

The image should be:
- Relevant to the section topic
- Professional and clean
- Suitable for a blog post
- Informative or illustrative"""

    return await generate_image(prompt)
